services:
  - type: web
    name: rag-agent-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: COLLECTION_NAME
        value: rag_embedding
      - key: DEBUG
        value: false